name: Custom

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: makeServiceAccKey
      run: |
        mkdir $HOME/private
        gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_PASS" \
        --output $HOME/private/services.tar services.tar.gpg
        tar xvf $HOME/private/services.tar -C $HOME/private
      env:
        FIREBASE_PASS: ${{ secrets.FIREBASE_PASS }}
    - name: Run firebaseParse.py
      run: |
        python firebaseParse.py
      env:
        FCM_TOKEN: ${{ secrets.FCM_TOKEN }}
        UNIPASS_TOKEN: ${{ secrets.UNIPASS_TOKEN }}
        EMS_TOKEN: ${{ secrets.EMS_TOKEN }}
